---
name: Crawl
'on':
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:

  Crawl:
    name: Crawl
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@main

      - name: Crawl the latest IPs list.
        run: |
          curl https://developers.google.com/search/apis/ipranges/googlebot.json -o googlebot.json -L
          curl https://developers.google.com/static/search/apis/ipranges/special-crawlers.json -o special-crawlers.json -L
          curl https://developers.google.com/static/search/apis/ipranges/user-triggered-fetchers.json -o user-triggered-fetchers.json -L

      - name: Separate into different formats and types.
        run: |
          jq -r '.prefixes[] | .ipv4Prefix' googlebot.json | grep -v null > "ipv4.txt"
          jq -r '.prefixes[] | .ipv4Prefix' special-crawlers.json | grep -v null >> "ipv4.txt"
          jq -r '.prefixes[] | .ipv4Prefix' user-triggered-fetchers.json | grep -v null >> "ipv4.txt"

          jq -r '.prefixes[] | .ipv6Prefix' googlebot.json | grep -v null > "ipv6.txt"
          jq -r '.prefixes[] | .ipv6Prefix' special-crawlers.json | grep -v null >> "ipv6.txt"
          jq -r '.prefixes[] | .ipv6Prefix' user-triggered-fetchers.json | grep -v null >> "ipv6.txt"

      - name: Create Pull Request.
        if: github.event_name != 'pull_request'
        id: cpr
        run: |
          if ! git diff --quiet; then
              git fetch
              if git rev-parse --verify origin/automatic_crawl >/dev/null 2>&1; then
                  git switch automatic_crawl
                  git pull
              else
                  git branch automatic_crawl
                  git switch automatic_crawl
              fi
              git config user.email "${{ github.actor }}@users.noreply.github.com"
              git config user.name "${{ github.actor }}"
              git commit -a -m "Automatic Crawl"
              git push -u origin automatic_crawl
              gh pr create --fill
              echo "pull-request-operation='created'" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Automerge if only json files have been changed
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: |
          if [[ ! $(git diff automatic_crawl..main --name-only | grep -vE "googlebot.json|special-crawlers.json|user-triggered-fetchers.json") ]]; then
              gh pr merge --merge --auto --delete-branch "${{ steps.cpr.outputs.pull-request-number }}"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
