---
name: Crawl
'on':
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:

  Crawl:
    name: Crawl
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@main

      - name: Crawl the latest IPs list.
        run: |
          curl https://developers.google.com/search/apis/ipranges/googlebot.json -o googlebot.json -L
          curl https://developers.google.com/static/search/apis/ipranges/special-crawlers.json -o special-crawlers.json -L
          curl https://developers.google.com/static/search/apis/ipranges/user-triggered-fetchers.json -o user-triggered-fetchers.json -L

      - name: Separate into different formats and types.
        run: |
          jq -r '.prefixes[] | .ipv4Prefix' googlebot.json | grep -v null > "ipv4.txt"
          jq -r '.prefixes[] | .ipv4Prefix' special-crawlers.json | grep -v null >> "ipv4.txt"
          jq -r '.prefixes[] | .ipv4Prefix' user-triggered-fetchers.json | grep -v null >> "ipv4.txt"

          jq -r '.prefixes[] | .ipv6Prefix' googlebot.json | grep -v null > "ipv6.txt"
          jq -r '.prefixes[] | .ipv6Prefix' special-crawlers.json | grep -v null >> "ipv6.txt"
          jq -r '.prefixes[] | .ipv6Prefix' user-triggered-fetchers.json | grep -v null >> "ipv6.txt"

      - name: Create Pull Request.
        if: github.event_name != 'pull_request'
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automatic Crawl
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: automatic_crawl
          delete-branch: true
          title: 'Automatic Crawl'
          draft: false

      - name: Automerge if only json files have been changed
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: |
          if [[ ! $(git diff automatic_crawl..main --name-only | grep -vE "googlebot.json|special-crawlers.json|user-triggered-fetchers.json") ]]; then
              gh pr merge --merge --auto --delete-branch "${{ steps.cpr.outputs.pull-request-number }}"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
